In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
from arch import arch_model
from scipy import stats
from statsmodels.stats.diagnostic import acorr_ljungbox
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import sys
import os
sys.path.append(os.path.abspath('..'))
from data.yfinance_data import fetch_data
from config import TRAIN_END, EVAL_START, EVAL_END

In [2]:
data = fetch_data()

[*********************100%***********************]  1 of 1 completed

In [3]:
prices = data['Adj Close']
returns = np.log(prices/prices.shift(1)).dropna()
log_returns = returns * 100
log_returns.columns = ['Log Percentage Returns']

In [4]:
log_returns.head()

            Log Percentage Returns
Date
2000-01-04               -3.909918
2000-01-05                0.192034
2000-01-06                0.095522
2000-01-07                2.672995
2000-01-10                1.112782

In [7]:
train_data = log_returns[:TRAIN_END]
eval_data = log_returns[EVAL_START:EVAL_END]

In [8]:
eval_data

            Log Percentage Returns
Date
2013-01-02                2.508612
2013-01-03               -0.208780
2013-01-04                0.485330
2013-01-07               -0.312800
2013-01-08               -0.324764
...                            ...
2025-12-23                0.454007
2025-12-24                0.321630
2025-12-26               -0.030441
2025-12-29               -0.349816
2025-12-30               -0.137661

[3269 rows x 1 columns]